version: '3.7'

services:
  postgresdb-fe:
    image: postgres:11.1
    environment:
      - POSTGRES_PASSWORD=secret
  api-fe:
    image: gcr.io/sa-todo-list/todo-api:latest
    links:
      - postgresdb-fe
    depends_on:
      - postgresdb-fe
    ports:
      - 8001:8000
    environment:
      - DB_HOST=postgresdb-fe
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_SSL_MODE=disable
      - SERVER_PORT=8000
      - CORS_ORIGINS=http://localhost:4201
  app:
    build:
      context: .
    depends_on:
      - api-fe
    ports:
      - 4201:80
